/**
 * generateReport(result) — creates a standalone HTML energy audit report
 * and triggers a browser download.
 *
 * result: AnalysisResponse from /analyze
 */
export function generateReport(result, filename = 'energy-audit.html') {
    if (!result) return

    const { risk_assessment: ra, extracted_features: ef, issues = [], suggestions = [] } = result
    const score = ra?.energy_risk_score ?? 0
    const level = ra?.risk_level ?? 'Unknown'
    const breakdown = ra?.risk_breakdown ?? {}
    const scoreColor = score >= 70 ? '#FF003C' : score >= 40 ? '#FFB000' : '#00FF41'
    const ts = new Date().toLocaleString()

    const issueRows = issues.map(i => `
    <tr>
      <td>${i.line}</td>
      <td>${i.type}</td>
      <td class="sev-${i.severity}">${i.severity.toUpperCase()}</td>
      <td>${i.message}</td>
    </tr>`).join('')

    const breakdownRows = Object.entries(breakdown).map(([k, v]) => `
    <tr>
      <td>${k.replace(/_/g, ' ').toUpperCase()}</td>
      <td>${v}</td>
      <td><div class="bar" style="width:${v}%; background:${scoreColor}"></div></td>
    </tr>`).join('')

    const sugsRows = suggestions.map((s, i) => `
    <li>[${i + 1}] ${s}</li>`).join('')

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>CodeEcoScan Energy Audit Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #0A0A0A; color: #C8C8C8; font-family: 'JetBrains Mono', monospace; padding: 40px; line-height: 1.6; }
  h1   { color: #00FF41; font-size: 22px; letter-spacing: 4px; margin-bottom: 4px; }
  h2   { color: #00FF41; font-size: 12px; letter-spacing: 2px; border-bottom: 1px solid #333; padding-bottom: 6px; margin: 28px 0 12px; }
  .meta { color: #6A6A6A; font-size: 10px; margin-bottom: 32px; }
  .score-big { font-size: 64px; font-weight: bold; color: ${scoreColor}; text-shadow: 0 0 20px ${scoreColor}80; display: inline-block; }
  .score-label { font-size: 12px; color: #6A6A6A; letter-spacing: 2px; margin-bottom: 32px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; margin-bottom: 16px; }
  th { background: #111; color: #6A6A6A; padding: 8px; text-align: left; letter-spacing: 1px; font-size: 10px; }
  td { padding: 8px; border-bottom: 1px solid #1A1A1A; }
  tr:hover td { background: #111; }
  .sev-high   { color: #FF003C; }
  .sev-medium { color: #FFB000; }
  .sev-low    { color: #00FF41; }
  .bar { height: 4px; background: #00FF41; max-width: 200px; min-width: 4px; }
  ul { list-style: none; }
  li { padding: 6px 0; border-bottom: 1px solid #1A1A1A; font-size: 11px; }
  .footer { margin-top: 48px; font-size: 10px; color: #3A3A3A; text-align: center; }
  .badge { display: inline-block; padding: 4px 12px; border: 1px solid ${scoreColor}; color: ${scoreColor}; font-size: 11px; letter-spacing: 2px; margin-left: 16px; }
</style>
</head>
<body>
<h1>CODEECOSCAN</h1>
<div class="meta">Energy Audit Report — Generated ${ts}</div>

<div class="score-big">${score}</div>
<span class="badge">/ 100 — ${level.toUpperCase()}</span>
<div class="score-label">ENERGY RISK SCORE</div>

<h2>SCORE BREAKDOWN</h2>
<table>
  <thead><tr><th>COMPONENT</th><th>SCORE</th><th>VISUAL</th></tr></thead>
  <tbody>${breakdownRows}</tbody>
</table>

<h2>ISSUES FOUND (${issues.length})</h2>
${issues.length ? `<table>
  <thead><tr><th>LINE</th><th>TYPE</th><th>SEVERITY</th><th>MESSAGE</th></tr></thead>
  <tbody>${issueRows}</tbody>
</table>` : '<p style="color:#6A6A6A;font-size:11px;padding:8px 0">No issues detected.</p>'}

<h2>OPTIMIZATION SUGGESTIONS</h2>
<ul>${sugsRows || '<li style="color:#6A6A6A">No suggestions.</li>'}</ul>

<h2>CODE FEATURES</h2>
<table>
  <thead><tr><th>FEATURE</th><th>VALUE</th></tr></thead>
  <tbody>
    <tr><td>MAX LOOP DEPTH</td><td>${ef?.max_loop_depth ?? '—'}</td></tr>
    <tr><td>NESTED LOOPS</td><td>${ef?.has_nested_loops ? 'YES' : 'NO'}</td></tr>
    <tr><td>CALLS INSIDE LOOPS</td><td>${ef?.function_calls_inside_loops ? 'YES' : 'NO'}</td></tr>
    <tr><td>HAS RECURSION</td><td>${ef?.has_recursion ? 'YES' : 'NO'}</td></tr>
    <tr><td>RECURSION INSIDE LOOP</td><td>${ef?.recursion_inside_loop ? 'YES' : 'NO'}</td></tr>
    <tr><td>HEAVY IMPORTS</td><td>${(ef?.heavy_imports_detected || []).join(', ') || 'NONE'}</td></tr>
  </tbody>
</table>

<div class="footer">Generated by CodeEcoScan — codeecoscan.onrender.com</div>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = filename; a.click()
    URL.revokeObjectURL(url)
}
